ongr_elasticsearch:
  analysis:
    filter:
      edge_ngram_filter: #-> your custom filter name to use in the analyzer below
        type: edge_ngram
        min_gram: 1
        max_gram: 20
    analyzer:
      eNgramAnalyzer: #-> analyzer name to use in the document field
        type: custom
        tokenizer: standard
        filter:
          - lowercase
          - edge_ngram_filter #that's the filter defined earlier
  indexes:
    App\Document\BookDocument:
      hosts: [http://%env(string:ELASTICSEARCH_HOST)%:%env(string:ELASTICSEARCH_PORT)%]