ongr_elasticsearch:
  analysis:
    filter:
      ngram_filter:
        type: nGram
        min_gram: 4
        max_gram: 4
    analyzer:
      NgramAnalyzer:
        type: custom
        tokenizer: standard
        filter:
          - lowercase
          - asciifolding
          - ngram_filter
  indexes:
    App\Document\BookDocument:
      hosts: [http://%env(string:ELASTICSEARCH_HOST)%:%env(string:ELASTICSEARCH_PORT)%]