security:
    encoders:
        App\Entity\User:
            algorithm: argon2i

    providers:
        entity_provider:
            entity:
                class: App\Entity\User
                property: email

    firewalls:
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false

        sign_in:
            pattern:  ^/api/auth/sign-in
            stateless: true
            anonymous: true
            json_login:
                username_path: email
                check_path: /api/auth/sign-in
                success_handler: lexik_jwt_authentication.handler.authentication_success
                failure_handler: lexik_jwt_authentication.handler.authentication_failure

        sign_up:
            pattern:  ^/api/auth/sign-up
            stateless: true
            anonymous: true

        api:
            pattern:  ^/api
            stateless: true
            anonymous: false
            provider: entity_provider
            guard:
                authenticators:
                    - lexik_jwt_authentication.jwt_token_authenticator

    access_control:
        - { path: ^/api/auth/sign-in, roles: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/api/auth/sign-up, roles: IS_AUTHENTICATED_ANONYMOUSLY }
