book_rate_post:
  path: /books/{bookId}/rate
  controller: App\Controller\Api\Book\RateController:upsertRate
  methods: [POST]

book_comments_get:
  path: /books/{bookId}/comments
  controller: App\Controller\Api\Book\CommentController:getCommentsByBookId
  methods: [GET]

book_comments_post:
  path: /books/{bookId}/comments
  controller: App\Controller\Api\Book\CommentController:createComment
  methods: [POST]

book_comments_put:
  path: /books/{bookId}/comments/{commentId}
  controller: App\Controller\Api\Book\CommentController:updateComment
  methods: [PUT]

book_comments_delete:
  path: /books/{bookId}/comments/{commentId}
  controller: App\Controller\Api\Book\CommentController:deleteComment
  methods: [DELETE]