user_profile_get:
  path: /user/profile
  controller: App\Controller\Api\User\UserController:getProfile
  methods: [GET]

user_profile_put:
  path: /user/profile
  controller: App\Controller\Api\User\UserController:updateProfile
  methods: [PUT]

user_book_post:
  path: /user/books
  controller: App\Controller\Api\User\UserBookController:saveUserBook
  methods: [POST]

user_book_get:
    path: /user/books/{userBookId}
    controller: App\Controller\Api\User\UserBookController:getUserBook
    methods: [GET]

user_book_put:
  path: /user/books/{userBookId}
  controller: App\Controller\Api\User\UserBookController:updateUserBook
  methods: [PUT]

user_book_delete:
  path: /user/books/{userBookId}
  controller: App\Controller\Api\User\UserBookController:deleteUserBook
  methods: [DELETE]

user_book_lists_post:
  path: /user/book/lists
  controller: App\Controller\Api\User\UserBookListController:saveUserBookList
  methods: [POST]

user_book_lists_put:
  path: /user/book/lists/{userBookListId}
  controller: App\Controller\Api\User\UserBookListController:updateUserBookList
  methods: [PUT]

user_book_lists_delete:
  path: /user/book/lists/{userBookListId}
  controller: App\Controller\Api\User\UserBookListController:deleteUserBookList
  methods: [DELETE]

user_book_tags_post:
  path: /user/book/tags
  controller: App\Controller\Api\User\UserBookTagController:saveUserBookTag
  methods: [POST]

user_book_tags_put:
  path: /user/book/tags/{userBookTagId}
  controller: App\Controller\Api\User\UserBookTagController:updateUserBookTag
  methods: [PUT]

user_book_tags_delete:
  path: /user/book/tags/{userBookTagId}
  controller: App\Controller\Api\User\UserBookTagController:deleteUserBookTag
  methods: [DELETE]