user_profile_get:
  path: /user/profile
  controller: App\Controller\Api\User\UserController:getProfile
  methods: [GET]

user_profile_put:
  path: /user/profile
  controller: App\Controller\Api\User\UserController:updateProfile
  methods: [PUT]

user_book_post:
  path: /user/books
  controller: App\Controller\Api\User\UserBookController:saveUserBook
  methods: [POST]

user_book_get:
    path: /user/books/{userBookId}
    controller: App\Controller\Api\User\UserBookController:getUserBook
    methods: [GET]

user_book_put:
  path: /user/books/{userBookId}
  controller: App\Controller\Api\User\UserBookController:updateUserBook
  methods: [PUT]

user_book_delete:
  path: /user/books/{userBookId}
  controller: App\Controller\Api\User\UserBookController:deleteUserBook
  methods: [DELETE]

user_book_lists_post:
  path: /user/book/lists
  controller: App\Controller\Api\User\UserBookListController:saveUserBookList
  methods: [POST]